package chaos.core.web.dao;

import chaos.core.web.model.ConfigModel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ConfigModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    @Delete({
        "delete from common_config",
        "where key = #{key,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_config (value)",
        "values (#{value,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="key", before=false, resultType=String.class)
    int insert(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    int insertSelective(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "key, value",
        "from common_config",
        "where key = #{key,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    ConfigModel selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_config
     *
     * @mbggenerated
     */
    @Update({
        "update common_config",
        "set value = #{value,jdbcType=LONGVARCHAR}",
        "where key = #{key,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(ConfigModel record);
}