package chaos.core.web.dao;

import chaos.core.web.model.EventInfoModel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface EventInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from common_event_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_event_info (name, type, ",
        "description)",
        "values (#{name,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(EventInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    int insertSelective(EventInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, type, description",
        "from common_event_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    EventInfoModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    @Update({
        "update common_event_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EventInfoModel record);

    @Select({"select * from common_event_info where name=#{name}"})
    @ResultMap("BaseResultMap")
    EventInfoModel selectByName(String name);
}