package chaos.core.web.dao;

import chaos.core.web.model.EventCacheModel;
import org.apache.ibatis.annotations.Insert;

public interface EventCacheModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_cache
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_event_cache (event_id, user_id, ",
        "unique_id, create_date)",
        "values (#{eventId,jdbcType=INTEGER}, #{userId,jdbcType=BIGINT}, ",
        "#{uniqueId,jdbcType=BIGINT}, #{createDate,jdbcType=VARCHAR})"
    })
    int insert(EventCacheModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_event_cache
     *
     * @mbggenerated
     */
    int insertSelective(EventCacheModel record);
}