package chaos.core.web.dao;

import chaos.core.web.model.EventsModel;
import org.apache.ibatis.annotations.Insert;

public interface EventsModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_events
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_events (event_id, create_date, ",
        "event_count)",
        "values (#{eventId,jdbcType=INTEGER}, #{createDate,jdbcType=VARCHAR}, ",
        "#{eventCount,jdbcType=BIGINT})"
    })
    int insert(EventsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_events
     *
     * @mbggenerated
     */
    int insertSelective(EventsModel record);
}