package chaos.core.web.dao;

import chaos.core.web.model.ExceptionModel;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ExceptionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_exceptions
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_exceptions (ip, user_id, ",
        "title, device, create_date, ",
        "context)",
        "values (#{ip,jdbcType=VARCHAR}, #{userId,jdbcType=BIGINT}, ",
        "#{title,jdbcType=VARCHAR}, #{device,jdbcType=VARCHAR}, #{createDate,jdbcType=VARCHAR}, ",
        "#{context,jdbcType=LONGVARCHAR})"
    })
    int insert(ExceptionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_exceptions
     *
     * @mbggenerated
     */
    int insertSelective(ExceptionModel record);

    @Select({"select * from common_exceptions"})
    @ResultMap("ResultMapWithBLOBs")
    List<ExceptionModel> selectAll();
}