package chaos.core.web.dao;

import chaos.core.web.model.LogModel;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface LogModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_logs
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_logs (user_name, user_id, ",
        "targetTable, type, ",
        "description, ip, ",
        "create_date)",
        "values (#{userName,jdbcType=VARCHAR}, #{userId,jdbcType=BIGINT}, ",
        "#{targettable,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{ip,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=VARCHAR})"
    })
    int insert(LogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_logs
     *
     * @mbggenerated
     */
    int insertSelective(LogModel record);

    LogModel selectByPrimaryKey(Long id);

    void getLogByUserID(long id);

    @Select({"select * from common_logs"})
    @ResultMap("BaseResultMap")
    List<LogModel> selectAll();
}