package chaos.core.web.dao;

import chaos.core.web.model.RegionModel;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface RegionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    @Delete({
        "delete from common_region",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_region (name, code, ",
        "parent_id)",
        "values (#{name,jdbcType=VARCHAR}, #{code,jdbcType=SMALLINT}, ",
        "#{parentId,jdbcType=SMALLINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Short.class)
    int insert(RegionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    int insertSelective(RegionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, code, parent_id",
        "from common_region",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    @ResultMap("BaseResultMap")
    RegionModel selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegionModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbggenerated
     */
    @Update({
        "update common_region",
        "set name = #{name,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=SMALLINT},",
          "parent_id = #{parentId,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(RegionModel record);

    @Select({"select * from common_region where parent_id = #{parentId}"})
    @ResultMap("BaseResultMap")
    List<RegionModel> selectByParentId(int parentId);
}