package chaos.core.web.dao;

import chaos.core.web.model.SmsModel;
import org.apache.ibatis.annotations.*;

public interface SmsModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sms",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sms (id, status, ",
        "content, type, ip, ",
        "phone, creat_date)",
        "values (#{id,jdbcType=BIGINT}, #{status,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{ip,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{creatDate,jdbcType=VARCHAR})"
    })
    int insert(SmsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    int insertSelective(SmsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, status, content, type, ip, phone, creat_date",
        "from sms",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    SmsModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    @Update({
        "update sms",
        "set status = #{status,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "creat_date = #{creatDate,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SmsModel record);
}