package chaos.core.web.dao;

import chaos.core.web.model.UpFileModel;
import org.apache.ibatis.annotations.*;

public interface UpFileModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    @Delete({
            "delete from common_up_file",
            "where code = #{code,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    @Insert({
        "insert into common_up_file (code, name, ",
        "path, status, file_type, ",
        "create_date)",
        "values (#{code,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=VARCHAR}, #{status,jdbcType=SMALLINT}, #{fileType,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=VARCHAR})"
    })
    int insert(UpFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    int insertSelective(UpFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "code, name, path, status, file_type, create_date",
            "from common_up_file",
            "where code = #{code,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    UpFileModel selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UpFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    @Update({
            "update common_up_file",
            "set name = #{name,jdbcType=VARCHAR},",
            "path = #{path,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=SMALLINT},",
            "file_type = #{fileType,jdbcType=VARCHAR},",
            "create_date = #{createDate,jdbcType=VARCHAR}",
            "where code = #{code,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UpFileModel record);


    @Select({
            "select",
            "code, name, path, status, file_type, create_date",
            "from common_up_file",
            "where code = #{code,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    UpFileModel selectByCode(String code);
}