package chaos.core.web.model;

import chaos.core.web.api.annoatation.ApiField;

import java.io.Serializable;

public class ConfigModel extends ParamsModel implements Serializable {
    /**
     * key唯一性
     */
    @ApiField("mapKey/key唯一性//")
    private String mapKey;

    /**
     * 内容建议使用json格式
     */
    @ApiField("mapValue/内容建议使用json格式//")
    private String mapValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * key唯一性
     */
    public String getMapKey() {
        return mapKey;
    }

    /**
     * key唯一性
     */
    public void setMapKey(String mapKey) {
        this.mapKey = mapKey == null ? null : mapKey.trim();
    }

    /**
     * 内容建议使用json格式
     */
    public String getMapValue() {
        return mapValue;
    }

    /**
     * 内容建议使用json格式
     */
    public void setMapValue(String mapValue) {
        this.mapValue = mapValue == null ? null : mapValue.trim();
    }
}