package chaos.core.web.model;

import java.io.Serializable;

public class EventInfoModel implements Serializable {
    /**
     * id
     */
    private Integer id;

    /**
     * 事件标题
     */
    private String name;

    /**
     * 类型1用户
     */
    private Integer type;

    /**
     * 事件描述
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_event_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     */
    public Integer getId() {
        return id;
    }

    /**
     * id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 事件标题
     */
    public String getName() {
        return name;
    }

    /**
     * 事件标题
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 类型1用户
     */
    public Integer getType() {
        return type;
    }

    /**
     * 类型1用户
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 事件描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 事件描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}