package chaos.core.web.model;

import java.io.Serializable;

public class EventCacheModel implements Serializable {
    /**
     * 事件id
     */
    private Integer eventId;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 其他唯一id
     */
    private Long uniqueId;

    /**
     * 创建时间
     */
    private String createDate = String.valueOf(System.currentTimeMillis());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_event_cache
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 事件id
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * 事件id
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * 用户id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 用户id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 其他唯一id
     */
    public Long getUniqueId() {
        return uniqueId;
    }

    /**
     * 其他唯一id
     */
    public void setUniqueId(Long uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * 创建时间
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * 创建时间
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }
}