package chaos.core.web.model;

import java.io.Serializable;

public class LogModel implements Serializable {
    /**
     * 用户名
     */
    private String userName;

    /**
     * 用户id
     */
    private Long userId;

    /**
     * 目标表
     */
    private String targettable;

    /**
     * 类型1添加，2删除，3修改
     */
    private Integer type;

    /**
     * 日志描述
     */
    private String description;

    /**
     * ip地址
     */
    private String ip;

    /**
     * 操作时间
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_logs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 用户id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 用户id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 目标表
     */
    public String getTargettable() {
        return targettable;
    }

    /**
     * 目标表
     */
    public void setTargettable(String targettable) {
        this.targettable = targettable == null ? null : targettable.trim();
    }

    /**
     * 类型1添加，2删除，3修改
     */
    public Integer getType() {
        return type;
    }

    /**
     * 类型1添加，2删除，3修改
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 日志描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 日志描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * ip地址
     */
    public String getIp() {
        return ip;
    }

    /**
     * ip地址
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 操作时间
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * 操作时间
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }
}