package chaos.core.web.model;

import java.io.Serializable;
import java.util.ArrayList;

public class RegionModel implements Serializable {
    private Short id;

    /**
     * 名字
     */
    private String name;

    /**
     * 区号
     */
    private Short code;

    /**
     * 上级id
     */
    private Short parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_region
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    private Iterable<? extends RegionModel> child = new ArrayList<>();

    /**
     * 
     */
    public Short getId() {
        return id;
    }

    /**
     * 
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * 名字
     */
    public String getName() {
        return name;
    }

    /**
     * 名字
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 区号
     */
    public Short getCode() {
        return code;
    }

    /**
     * 区号
     */
    public void setCode(Short code) {
        this.code = code;
    }

    /**
     * 上级id
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * 上级id
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    public Iterable<? extends RegionModel> getChild() {
        return child;
    }

    public void setChild(Iterable<? extends RegionModel> child) {
        this.child = child;
    }
}