package chaos.core.web.model;

import java.io.Serializable;

public class SmsModel extends ParamsModel implements Serializable {
    /**
     * id
     */
    private Long id;

    /**
     * 0待发送 1 发送成功。
     */
    private Integer status;

    /**
     * 内容长度255
     */
    private String content;

    /**
     * 1验证码 2重置码
     */
    private Integer type;

    /**
     * 公网ip地址
     */
    private String ip;

    /**
     * 手机
     */
    private String phone;

    /**
     * 提交时间
     */
    private String creatDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     */
    public Long getId() {
        return id;
    }

    /**
     * id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 0待发送 1 发送成功。
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 0待发送 1 发送成功。
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 内容长度255
     */
    public String getContent() {
        return content;
    }

    /**
     * 内容长度255
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * 1验证码 2重置码
     */
    public Integer getType() {
        return type;
    }

    /**
     * 1验证码 2重置码
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 公网ip地址
     */
    public String getIp() {
        return ip;
    }

    /**
     * 公网ip地址
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * 手机
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 手机
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 提交时间
     */
    public String getCreatDate() {
        return creatDate;
    }

    /**
     * 提交时间
     */
    public void setCreatDate(String creatDate) {
        this.creatDate = creatDate == null ? null : creatDate.trim();
    }
}