package chaos.core.web.model;

import chaos.core.web.api.annoatation.ApiField;

import java.io.Serializable;

public class UpFileModel implements Serializable {
    /**
     * 文件名称
     */
    @ApiField("name/文件名称//")
    private String name;

    /**
     * 文件分类
     */
    @ApiField("path/文件分类//")
    private String path;

    /**
     * 文件上传状态0~100，100为上传完成。
     */
    @ApiField("status/文件上传状态0~100，100为上传完成。//")
    private Short status;

    /**
     * 文件类型，0图片，1文档
     */
    @ApiField("fileType/文件类型，0图片，1文档//")
    private String fileType;

    /**
     * 唯一标示，每个文件唯一
     */
    @ApiField("code/唯一标示，每个文件唯一//")
    private String code;

    /**
     * 创建时间
     */
    @ApiField("createDate/创建时间//")
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table common_up_file
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 文件名称
     */
    public String getName() {
        return name;
    }

    /**
     * 文件名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 文件分类
     */
    public String getPath() {
        return path;
    }

    /**
     * 文件分类
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * 文件上传状态0~100，100为上传完成。
     */
    public Short getStatus() {
        return status;
    }

    /**
     * 文件上传状态0~100，100为上传完成。
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * 文件类型，0图片，1文档
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * 文件类型，0图片，1文档
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * 唯一标示，每个文件唯一
     */
    public String getCode() {
        return code;
    }

    /**
     * 唯一标示，每个文件唯一
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 创建时间
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * 创建时间
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }
}